name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/html
            # rm -R 4d
            # git clone repo
            # mv 4D-Integrasi/ 4d/
            # cp .env_4D 4d/.env
            # chown -R www-data:www-data 4d/
            # chmod -R 755 4d/
            # cd 4d
            # composer update
            # php artisan migrate:refresh --seed
            exit
